use crate::ast::*;
grammar;

// 约束 lexer 的行为
match {
  // 跳过空白符和注释
  r"\s*" => {},
  r"//[^\n\r]*[\n\r]*" => {},
  r"/\*[^*/]*\*/" => {},
  // 剩下的情况采用默认方式处理
  _
}

// 定义 CompUnit, 其返回值类型为 CompUnit
// parser 在解析完成后的行为是返回 FuncDef 的值
pub CompUnit: CompUnit = <func_def: FuncDef> => CompUnit {
    func_def,
};

FuncDef: FuncDef = {
  <func_type: FuncType> <ident: Ident> "(" ")" <block: Block> => FuncDef {
    func_type,
    ident,
    block,
  }
}

FuncType: FuncType = "int" => FuncType {
    _type: "int".to_string()
};

// Declarations
Decl: Decl = {
  <const_decl: ConstDecl> => Decl::Const(const_decl),
  <var_decl: VarDecl>     => Decl::Var(var_decl),
};

ConstDecl: ConstDecl = "const" <btype: BType> <defs: ConstDefList> ";" => ConstDecl {
    btype,
    const_defs: defs,
};

ConstDefList: Vec<ConstDef> = {
  <first: ConstDef> <rest: ("," <ConstDef>)*> => {
    let mut v = vec![first];
    for d in rest { v.push(d); }
    v
  }
};

BType: BType = "int" => BType { _type: "int".to_string() };

ConstDef: ConstDef = <ident: Ident> "=" <val: ConstInitVal> => ConstDef {
  ident,
  const_val: val,
};

ConstInitVal: ConstInitVal = <ce: ConstExp> => ConstInitVal { const_exp: ce };

ConstExp: ConstExp = <exp: Exp> => ConstExp { exp };

// VarDecl and VarDef
VarDecl: VarDecl = <btype: BType> <defs: VarDefList> ";" => VarDecl {
  b_type: btype,
  var_defs: defs,
};

VarDefList: Vec<VarDef> = {
  <first: VarDef> <rest: ("," <VarDef>)*> => {
    let mut v = vec![first];
    for d in rest { v.push(d); }
    v
  }
};

VarDef: VarDef = {
  <ident: Ident> => VarDef::Decl(ident),
  <ident: Ident> "=" <init: InitVal> => VarDef::Init(ident, init),
};

InitVal: InitVal = <exp: Exp> => InitVal { exp };

// Block and items
Block: Block = "{" <block_items: BlockItemList> "}" => Block { block_items };

BlockItemList: Vec<BlockItem> = <items: (<BlockItem>)*> => items;

BlockItem: BlockItem = {
  <decl: Decl> => BlockItem::Decl(decl),
  <stmt: Stmt> => BlockItem::Stmt(stmt),
};

// Statements
Stmt: Stmt = {
  <lval: LVal> "=" <exp: Exp> ";" => Stmt::Assign(lval, exp),
  <exp: Exp?> ";" => Stmt::Exp(exp),
  <block: Block> => Stmt::Block(block),
  "return" <exp: Exp?> ";" => Stmt::Return(exp),
};

Exp: Exp = <lor_exp: LOrExp> => Exp {
  lor_exp
};

UnaryExp: UnaryExp = {
  <primary_exp: PrimaryExp> => UnaryExp::Primary(primary_exp),
  "+" <unary_exp: UnaryExp> => UnaryExp::Positive(Box::new(unary_exp)),
  "-" <unary_exp: UnaryExp> => UnaryExp::Negative(Box::new(unary_exp)),
  "!" <unary_exp: UnaryExp> => UnaryExp::Not(Box::new(unary_exp)),
};

// LVal and PrimaryExp extension
LVal: LVal = <ident: Ident> => LVal { ident };

PrimaryExp: PrimaryExp = {
  "(" <exp: Exp> ")" => PrimaryExp::Paren(Box::new(exp)),
  <lval: LVal> => PrimaryExp::LVal(lval),
  <num: Number> => PrimaryExp::Number(num),
}

Number: i32 = <num: IntConst> => num;

AddExp: AddExp = {
  <mul_exp: MulExp> => AddExp::Mul(mul_exp),
  <add_exp: AddExp> "+" <mul_exp: MulExp> => AddExp::Add(Box::new(add_exp), mul_exp),
  <add_exp: AddExp> "-" <mul_exp: MulExp> => AddExp::Sub(Box::new(add_exp), mul_exp),
}

MulExp: MulExp = {
  <unary: UnaryExp> => MulExp::Unary(unary),
  <mul_exp: MulExp> "*" <unary: UnaryExp> => MulExp::Mul(Box::new(mul_exp), unary),
  <mul_exp: MulExp> "/" <unary: UnaryExp> => MulExp::Div(Box::new(mul_exp), unary),
  <mul_exp: MulExp> "%" <unary: UnaryExp> => MulExp::Mod(Box::new(mul_exp), unary),
}

LOrExp: LOrExp = {
  <land: LAndExp> => LOrExp::And(land),
  <lor: LOrExp> "||" <land: LAndExp> => LOrExp::Or(Box::new(lor), land),
}

LAndExp: LAndExp = {
  <eq: EqExp> => LAndExp::Eq(eq),
  <land: LAndExp> "&&" <eq: EqExp> => LAndExp::And(Box::new(land), eq),
}

EqExp: EqExp = {
  <rel: RelExp> => EqExp::Rel(rel),
  <eq_exp: EqExp> "==" <rel: RelExp> => EqExp::Eq(Box::new(eq_exp), rel),
  <eq_exp: EqExp> "!=" <rel: RelExp> => EqExp::Neq(Box::new(eq_exp), rel),
}

RelExp: RelExp = {
  <add: AddExp> => RelExp::Add(add),
  <rel: RelExp> "<" <add: AddExp> => RelExp::Lt(Box::new(rel), add),
  <rel: RelExp> ">" <add: AddExp> => RelExp::Gt(Box::new(rel), add),
  <rel: RelExp> ">=" <add: AddExp> => RelExp::Ge(Box::new(rel), add),
  <rel: RelExp> "<=" <add: AddExp> => RelExp::Le(Box::new(rel), add),
}

// 如果匹配到标识符, 就返回这个字符串
// 一对尖括号在此处指代的是正则表达式匹配到的字符串 (&str)
// 关于尖括号到底代表什么, 请 RTFM
Ident: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

// 对整数字面量的处理方式: 把匹配到的字符串按对应进制转换成数字
IntConst: i32 = {
  r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
  r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
  r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}
