use crate::ast::*;
grammar;

// 约束 lexer 的行为
match {
  // 跳过空白符和注释
  r"\s*" => {},
  r"//[^\n\r]*[\n\r]*" => {},
  r"/\*[^*/]*\*/" => {},
  // 剩下的情况采用默认方式处理
  _
}

// 定义 CompUnit, 其返回值类型为 CompUnit
// CompUnit ::= [CompUnit] (Decl | FuncDef);
pub CompUnit: CompUnit = <comp_unit: CompUnit?> <body: CompBody> => CompUnit {
    comp_unit: Box::new(comp_unit),
    body,
};

// CompBody 可以是函数定义或声明
CompBody: CompBody = {
    <func_type: TypeSpec> <ident: Ident> "(" <params: FuncFParams?> ")" <block: Block> => {
        let func_type = match func_type.as_str() {
            "int" => FuncType::Int,
            "void" => FuncType::Void,
            _ => panic!("Unknown function type"),
        };
        CompBody::FuncDef(FuncDef {
            func_type,
            ident,
            params,
            block,
        })
    },
    // 常量声明
    "const" <btype: TypeSpec> <defs: ConstDefList> ";" => {
        CompBody::Decl(Decl::Const(ConstDecl {
            btype: BType { _type: btype },
            const_defs: defs,
        }))
    },
    // 变量声明
    <btype: TypeSpec> <defs: VarDefList> ";" => {
        CompBody::Decl(Decl::Var(VarDecl {
            b_type: BType { _type: btype },
            var_defs: defs,
        }))
    },
};

TypeSpec: String = {
    "int" => "int".to_string(),
    "void" => "void".to_string(),
};

FuncFParams: FuncFParams = <params: TList<FuncFParam>> => FuncFParams { params };

// FuncFParam ::= BType IDENT ["[" "]" {"[" ConstExp "]"}];
FuncFParam: FuncFParam = {
  // 非数组参数：int x
  <b_type: TypeSpec> <ident: Ident> => FuncFParam {
    b_type: BType { _type: b_type },
    ident,
    indexs: None,
  },
  // 数组参数：int x[][3][4]
  <b_type: TypeSpec> <ident: Ident> "[" "]" <dims: ("[" <ConstExp> "]")*> => FuncFParam {
    b_type: BType { _type: b_type },
    ident,
    indexs: Some(dims),
  },
};

// Declarations
Decl: Decl = {
  <const_decl: ConstDecl> => Decl::Const(const_decl),
  <var_decl: VarDecl>     => Decl::Var(var_decl),
};

ConstDecl: ConstDecl = "const" <btype: TypeSpec> <defs: ConstDefList> ";" => ConstDecl {
    btype: BType { _type: btype },
    const_defs: defs,
};

ConstDefList: Vec<ConstDef> = TList<ConstDef>;

ConstDef: ConstDef = <ident: Ident> <size: ("[" <ConstExp> "]")*> "=" <val: ConstInitVal> 
=> ConstDef {
  ident,
  size,
  const_val: val,
};

ConstInitVal: ConstInitVal = {
  <ce: ConstExp> => ConstInitVal::Var(ce),
  "{" <vci: ConstInitValList> "}" => ConstInitVal::Array(vci),
};

ConstInitValList: Vec<ConstInitVal> = TListOpt<ConstInitVal>;

ConstExp: ConstExp = <exp: Exp> => ConstExp { exp };

ConstExpList: Vec<ConstExp> = TList<ConstExp>;

// VarDecl and VarDef
VarDecl: VarDecl = <btype: TypeSpec> <defs: VarDefList> ";" => VarDecl {
  b_type: BType { _type: btype },
  var_defs: defs,
};

VarDefList: Vec<VarDef> = TList<VarDef>;

VarDef: VarDef = {
  <ident: Ident> <index: ("[" <ConstExp> "]")*> "=" <init: InitVal> 
    => VarDef::Init(ident, index, init),
  <ident: Ident> <index: ("[" <ConstExp> "]")*> 
    => VarDef::Decl(ident, index),
};

InitVal: InitVal = {
  <exp: Exp> => InitVal::Var(exp),
  "{" <exps: InitValList> "}" => InitVal::Array(exps),
}

InitValList: Vec<InitVal> = TListOpt<InitVal>;

// Block and items
Block: Block = "{" <block_items: BlockItemList> "}" => Block { block_items };

BlockItemList: Vec<BlockItem> = <items: (<BlockItem>)*> => items;

BlockItem: BlockItem = {
  <decl: Decl> => BlockItem::Decl(decl),
  <stmt: Stmt> => BlockItem::Stmt(stmt),
};

Stmt: Stmt = {
  <matched: MatchedStmt> => matched,
  <unmatched: UnmatchedStmt> => unmatched,
};

// Statements
MatchedStmt: Stmt = {
  <lval: LVal> "=" <exp: Exp> ";" => Stmt::Assign(lval, exp),
  <exp: Exp?> ";" => Stmt::Exp(exp),
  <block: Block> => Stmt::Block(block),
  "if" "(" <exp: Exp> ")" <body: MatchedStmt> "else" <else_body: MatchedStmt> => {
    Stmt::If(exp, Box::new(body), Some(Box::new(else_body)))
  },
  "while" "(" <exp: Exp> ")" <stmt: MatchedStmt> => Stmt::While(exp, Box::new(stmt)),
  "break" ";" => Stmt::Break,
  "continue" ";" => Stmt::Continue,
  "return" <exp: Exp?> ";" => Stmt::Return(exp),
};

UnmatchedStmt: Stmt = {
  "if" "(" <exp: Exp> ")" <body: Stmt> => {
    Stmt::If(exp, Box::new(body), None)
  },
  "if" "(" <exp: Exp> ")" <body: MatchedStmt> "else" <else_body: UnmatchedStmt> => {
    Stmt::If(exp, Box::new(body), Some(Box::new(else_body)))
  },
  "while" "(" <exp: Exp> ")" <stmt: UnmatchedStmt> => Stmt::While(exp, Box::new(stmt)),
}

Exp: Exp = <lor_exp: LOrExp> => Exp {
  lor_exp
};

ExpList: Vec<Exp> = TListOpt<Exp>;

UnaryExp: UnaryExp = {
  <primary_exp: PrimaryExp> => UnaryExp::Primary(primary_exp),
  <ident: Ident> "(" <rparams: FuncRParams?> ")" => UnaryExp::FuncCall(ident, rparams),
  "+" <unary_exp: UnaryExp> => UnaryExp::Positive(Box::new(unary_exp)),
  "-" <unary_exp: UnaryExp> => UnaryExp::Negative(Box::new(unary_exp)),
  "!" <unary_exp: UnaryExp> => UnaryExp::Not(Box::new(unary_exp)),
};

FuncRParams: FuncRParams = <params: TList<Exp>> => FuncRParams { params };

// LVal and PrimaryExp extension
LVal: LVal = <ident: Ident> <index: ("[" <Exp> "]")*>
  => LVal { ident, index: Box::new(index) };

PrimaryExp: PrimaryExp = {
  "(" <exp: Exp> ")" => PrimaryExp::Paren(Box::new(exp)),
  <lval: LVal> => PrimaryExp::LVal(lval),
  <num: Number> => PrimaryExp::Number(num),
}

Number: i32 = <num: IntConst> => num;

AddExp: AddExp = {
  <mul_exp: MulExp> => AddExp::Mul(mul_exp),
  <add_exp: AddExp> "+" <mul_exp: MulExp> => AddExp::Add(Box::new(add_exp), mul_exp),
  <add_exp: AddExp> "-" <mul_exp: MulExp> => AddExp::Sub(Box::new(add_exp), mul_exp),
}

MulExp: MulExp = {
  <unary: UnaryExp> => MulExp::Unary(unary),
  <mul_exp: MulExp> "*" <unary: UnaryExp> => MulExp::Mul(Box::new(mul_exp), unary),
  <mul_exp: MulExp> "/" <unary: UnaryExp> => MulExp::Div(Box::new(mul_exp), unary),
  <mul_exp: MulExp> "%" <unary: UnaryExp> => MulExp::Mod(Box::new(mul_exp), unary),
}

LOrExp: LOrExp = {
  <land: LAndExp> => LOrExp::And(land),
  <lor: LOrExp> "||" <land: LAndExp> => LOrExp::Or(Box::new(lor), land),
}

LAndExp: LAndExp = {
  <eq: EqExp> => LAndExp::Eq(eq),
  <land: LAndExp> "&&" <eq: EqExp> => LAndExp::And(Box::new(land), eq),
}

EqExp: EqExp = {
  <rel: RelExp> => EqExp::Rel(rel),
  <eq_exp: EqExp> "==" <rel: RelExp> => EqExp::Eq(Box::new(eq_exp), rel),
  <eq_exp: EqExp> "!=" <rel: RelExp> => EqExp::Neq(Box::new(eq_exp), rel),
}

RelExp: RelExp = {
  <add: AddExp> => RelExp::Add(add),
  <rel: RelExp> "<" <add: AddExp> => RelExp::Lt(Box::new(rel), add),
  <rel: RelExp> ">" <add: AddExp> => RelExp::Gt(Box::new(rel), add),
  <rel: RelExp> ">=" <add: AddExp> => RelExp::Ge(Box::new(rel), add),
  <rel: RelExp> "<=" <add: AddExp> => RelExp::Le(Box::new(rel), add),
}

// 如果匹配到标识符, 就返回这个字符串
// 一对尖括号在此处指代的是正则表达式匹配到的字符串 (&str)
// 关于尖括号到底代表什么, 请 RTFM
Ident: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

// 对整数字面量的处理方式: 把匹配到的字符串按对应进制转换成数字
IntConst: i32 = {
  r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
  r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
  r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}

// 泛型非终结符：以逗号连接元素
TList<T>: Vec<T> = {
  <first: T> <rest: ("," <T>)*> => {
    let mut v = vec![first];
    for d in rest { v.push(d); }
    v
  }
};

// 可选的列表（可以为空）
TListOpt<T>: Vec<T> = {
  => vec![],
  <list: TList<T>> => list,
};
